/*  isp-interrupt.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/of_irq.h>
/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("isp-interrupt - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "isp-interrupt"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";
unsigned int*       irqclr_reg_addr;
module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct isp_interrupt_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t isp_interrupt_irq(int irq, void *lp)
{
	printk("momenta,isp-interrupt isp-interrupt interrupt\n");
	//clear the interrupt flag
	*irqclr_reg_addr = 0xffffffff;
	return IRQ_HANDLED;
}

static int isp_interrupt_probe(struct platform_device *pdev)
{
#if 0
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct isp_interrupt_local *lp = NULL;

	int rc = 0;
	struct device_node *nd;
	printk(" isp-interrupt probe\n");
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */

	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct isp_interrupt_local *) kmalloc(sizeof(struct isp_interrupt_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate isp-interrupt device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "isp-interrupt: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	printk(" irq=%d\n",r_irq);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "isp-interrupt at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	printk(" request_irq irq=%d\n",lp->irq);
	rc = request_irq(lp->irq, &isp_interrupt_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"isp-interrupt at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
#endif
	int irq;
	unsigned int reg;
	struct device_node *nd;
	printk("momenta,isp-interrupt isp-interrupt probe\n");
	nd = of_find_node_by_path("/ispmonitor");
	if(0 > of_property_read_u32(nd, "irq-clr", &reg)) {
        printk("momenta,isp-interrupt can not get irq-clr\n");
        return -EINVAL;
    }
	printk("momenta,isp-interrupt irq-clr reg=0x%08x\n",reg);
    irqclr_reg_addr = (unsigned int *)ioremap_wc(reg, sizeof(unsigned int *));
    printk("momenta,isp-interrupt ispmonitor/remap: 0x%08x/0x%lx\n", reg, (unsigned long)irqclr_reg_addr);
	irq = of_irq_get(nd, 0);
	printk("momenta,isp-interrupt node irq=%d\n",irq);
	if (irq < 0) {
		printk("momenta,isp-interrupt irq error\n");
		irq = 0;
	}else{
		printk("momenta,isp-interrupt request_irq success\n");
		request_irq(irq, &isp_interrupt_irq, 1, "ispmonitor", NULL);
	}
	return 0;
	free_irq(irq, NULL);
	return -1;
}

static int isp_interrupt_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct isp_interrupt_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id isp_interrupt_of_match[] = {
	{ .compatible = "momenta,isp-interrupt", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, isp_interrupt_of_match);
#else
# define isp_interrupt_of_match
#endif


static struct platform_driver isp_interrupt_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= isp_interrupt_of_match,
	},
	.probe		= isp_interrupt_probe,
	.remove		= isp_interrupt_remove,
};

static int __init isp_interrupt_init(void)
{
	printk("<1>momenta,isp-interrupt init.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&isp_interrupt_driver);
}


static void __exit isp_interrupt_exit(void)
{
	platform_driver_unregister(&isp_interrupt_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

//module_init(isp_interrupt_init);
//module_exit(isp_interrupt_exit);
